#!/bin/sh

rm -f Multi-Job-Ended-1
touch Multi-Job-Started
export TURBODIR=/lustre/lusitania_homes/ubu-iccram/ubu-iccram01/MASTER_SALUD_2026/TmoleX2024/TURBOMOLE
export PATH=$TURBODIR/scripts:$PATH
ulimit -s unlimited &> /dev/null
if [ $? -ne 0 ]; then
ulimit -s 1048576 &> /dev/null
if [ $? -ne 0 ]; then
echo "WARNING: Could not set stack size!"
echo "         Some jobs might fail to run, please check size limit."
echo "         Output of ulimit -s is:"ulimit -s
fi
fi
export PATH=$TURBODIR/bin/`sysname`:$PATH
export PERL_BADLANG=0
cd "opt_final_PSS_styrene_sulfonate_monomer_5"
if [ $? -eq 0 ]; then
touch "opt_final_PSS_styrene_sulfonate_monomer_5_Job_Started"
touch SP_Job_Start
ridft >ridft.out
aoforce >aoforce.out
rm -f SP_Job_Start
touch SP_Job_End
replacequote.sh
if [ "$PWD" = "$HOME" ]; then
echo "I'm sorry, Dave. I'm afraid I can't do that. (not in this directory)"
else
 if [ -e control ]; then
ls * > tmp1
for i in `grep -E -v "" tmp1`
do
 rm -f $i
done
rm -f tmp1
rm -rf MPI-TEMPDIR*
fi
fi
rm -f "opt_final_PSS_styrene_sulfonate_monomer_5_Job_Started.gz"
rm -f "opt_final_PSS_styrene_sulfonate_monomer_5_Job_Started"
touch "opt_final_PSS_styrene_sulfonate_monomer_5_Job_Ended"
cd ..
fi
cd "opt_final_Tris_buffer_Tris_base_6"
if [ $? -eq 0 ]; then
touch "opt_final_Tris_buffer_Tris_base_6_Job_Started"
touch SP_Job_Start
ridft >ridft.out
aoforce >aoforce.out
rm -f SP_Job_Start
touch SP_Job_End
replacequote.sh
if [ "$PWD" = "$HOME" ]; then
echo "I'm sorry, Dave. I'm afraid I can't do that. (not in this directory)"
else
 if [ -e control ]; then
ls * > tmp1
for i in `grep -E -v "" tmp1`
do
 rm -f $i
done
rm -f tmp1
rm -rf MPI-TEMPDIR*
fi
fi
rm -f "opt_final_Tris_buffer_Tris_base_6_Job_Started.gz"
rm -f "opt_final_Tris_buffer_Tris_base_6_Job_Started"
touch "opt_final_Tris_buffer_Tris_base_6_Job_Ended"
cd ..
fi
cd "opt_final_HEPES_7"
if [ $? -eq 0 ]; then
touch "opt_final_HEPES_7_Job_Started"
touch SP_Job_Start
ridft >ridft.out
aoforce >aoforce.out
rm -f SP_Job_Start
touch SP_Job_End
replacequote.sh
if [ "$PWD" = "$HOME" ]; then
echo "I'm sorry, Dave. I'm afraid I can't do that. (not in this directory)"
else
 if [ -e control ]; then
ls * > tmp1
for i in `grep -E -v "" tmp1`
do
 rm -f $i
done
rm -f tmp1
rm -rf MPI-TEMPDIR*
fi
fi
rm -f "opt_final_HEPES_7_Job_Started.gz"
rm -f "opt_final_HEPES_7_Job_Started"
touch "opt_final_HEPES_7_Job_Ended"
cd ..
fi
cd "opt_final_PVP_monomer_N-vinyl-2-pyrrolidone_8"
if [ $? -eq 0 ]; then
touch "opt_final_PVP_monomer_N-vinyl-2-pyrrolidone_8_Job_Started"
touch SP_Job_Start
ridft >ridft.out
aoforce >aoforce.out
rm -f SP_Job_Start
touch SP_Job_End
replacequote.sh
if [ "$PWD" = "$HOME" ]; then
echo "I'm sorry, Dave. I'm afraid I can't do that. (not in this directory)"
else
 if [ -e control ]; then
ls * > tmp1
for i in `grep -E -v "" tmp1`
do
 rm -f $i
done
rm -f tmp1
rm -rf MPI-TEMPDIR*
fi
fi
rm -f "opt_final_PVP_monomer_N-vinyl-2-pyrrolidone_8_Job_Started.gz"
rm -f "opt_final_PVP_monomer_N-vinyl-2-pyrrolidone_8_Job_Started"
touch "opt_final_PVP_monomer_N-vinyl-2-pyrrolidone_8_Job_Ended"
cd ..
fi
cd "opt_final_Polyethyleneimine_fragment_ethylenediamine_9"
if [ $? -eq 0 ]; then
touch "opt_final_Polyethyleneimine_fragment_ethylenediamine_9_Job_Started"
touch SP_Job_Start
ridft >ridft.out
aoforce >aoforce.out
rm -f SP_Job_Start
touch SP_Job_End
replacequote.sh
if [ "$PWD" = "$HOME" ]; then
echo "I'm sorry, Dave. I'm afraid I can't do that. (not in this directory)"
else
 if [ -e control ]; then
ls * > tmp1
for i in `grep -E -v "" tmp1`
do
 rm -f $i
done
rm -f tmp1
rm -rf MPI-TEMPDIR*
fi
fi
rm -f "opt_final_Polyethyleneimine_fragment_ethylenediamine_9_Job_Started.gz"
rm -f "opt_final_Polyethyleneimine_fragment_ethylenediamine_9_Job_Started"
touch "opt_final_Polyethyleneimine_fragment_ethylenediamine_9_Job_Ended"
cd ..
fi

rm -f Multi-Job-Started.gz
rm -f Multi-Job-Started
touch Multi-Job-Ended-1
